-- SQL para criar o banco e tabela
CREATE DATABASE IF NOT EXISTS product_manager CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE product_manager;

CREATE TABLE IF NOT EXISTS products (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  price DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  category VARCHAR(100) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
